services:
  - name: flask-app
    type: web
    env: python
    plan: free # Change if using a paid plan
    region: oregon # Choose your preferred region
    buildCommand: pip install -r requirements.txt
    startCommand: python -m waitress --listen=0.0.0.0:$PORT app:app
    envVars:
      - key: PORT
        value: 5000 # Render assigns a dynamic port, so this is just a fallback
    autoDeploy: true # Automatically deploy on Git updates
